### ISSUE TITLE
Case sensitivity of "Term Source Ref"

### ISSUE THREAD

**Issue by bobular** [ISA-tools/OntoMaton#11]
The auto insert functionality requires "Term Source Ref" to be in the column heading and unfortunately "Term Source REF" does not work as expected.  Searching on the web and from my recollection of the ISA-Tab specification, "REF" is the prefered form, although I am more than happy for the test here to be case insensitive.

**Comment by agbeltran** [comment]
This was fixed and it is available in the live version.
