### ISSUE TITLE
pb with settings in Ontomaton

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/OntoMaton#14]
caused by:
Request failed for http://lov.okfn.org/dataset/lov/api/v1/vocabs returned code 404. Truncated server response: <!DOCTYPE html> <html lang="en"> <head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> <meta charset="utf-8"> <m... (use muteHttpExceptions option to examine full response).

**Comment by ellis** [comment]
Same problem here -- can't access the OntoMaton settings.  There was a little more text in my error message, so I'll include that:

```
Request failed for http://lov.okfn.org/dataset/lov/api/v1/vocabs returned code 404. Truncated server response: <!DOCTYPE html> <html lang="en"> <head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> <meta charset="utf-8"> <m... (use muteHttpExceptions option to examine full response).
```

**Comment by agbeltran** [comment]
We need to upgrade to LOV API v2. I will fix this asap.

**Comment by agbeltran** [comment]
Related to #13

**Comment by proccaserra** [comment]
searching with ontomaton over Bioportal currently throw repeated error messages but if one persists, the search is successful. 
However, the user experience is obviously painful: 
for term 'patient' used as search token:
I received the following individual /sequential messages until eventual search success (phew!):
SyntaxError: Unexpected token in object literal
SyntaxError: Expected : found a
SyntaxError: Expected : found a
SyntaxError: Expected : found ,
SyntaxError: Unexpected token in object literal
SyntaxError: Unexpected token in object literal
SyntaxError: Missing comma in array literal
SyntaxError: Expected : found }
SyntaxError: Unexpected token in object literal
SyntaxError: Unexpected token in object literal
SyntaxError: Expected : found a
SyntaxError: Unexpected token in object literal
SyntaxError: Unexpected token in object literal
SyntaxError: Missing comma in array literal
SyntaxError: Expected : found }

was working fine until recently , though

**Comment by eamonnmag** [comment]
This is I believe something to do with the caching system. But I need to check.

---
Dr. Eamonn Maguire

**Comment by eamonnmag** [comment]
So, the actual problem was caused by the query to bioportal to get the ontologies. The query result was over 6MB! I filtered out the request to have only what we need with some useful new parameters they added, and now the request size is down to ~600KB. It will take a few hours for your cache to expire. But in the morning, give it a try and see how it goes. Everything should be much faster.

**Comment by eamonnmag** [comment]
LOV Still has some search issues. Will look in to them later on this evening. BioPortal appears to work well again, and much quicker.

**Comment by proccaserra** [comment]
Thx Eamonn for looking and fixing the stuff. So It worked perfectly a few hours ago, it was fast , much, much faster!
... but now I am getting errors again from Bioportal calls (See below).

Errors on bioportal: 
SyntaxError: Unexpected token in object literal
SyntaxError: Expected : found ,
SyntaxError: Expected : found ,
SyntaxError: Unexpected token in object literal
SyntaxError: Expected : found ,
SyntaxError: Missing comma in array literal
SyntaxError: Expected end of stream at char 4

and if I am too keen, I get the following:
Exception: Service invoked too many times in a short time: cacheService rateMax. Try Utilities.sleep(1000) between calls.

Also, Alejandra is looking into LOV as they changes their API to v2.

one side question: are whitespace separated string token accepted as search inputs or does it have to be single word searches?

Thank you Dr E :)

**Comment by eamonnmag** [comment]
LOV is already upgraded to version 2. It was working before. There is some strange behaviour now happening with the cache and *i think* reparsing the cache result using JSON.parse. It shall be solved.

**Comment by proccaserra** [comment]
more problems. today ontomaton returns 'aspirin' for all my searches. search on LOV worked once, then error messages such as:
This was on Chrome.

Add-on does not seem to work on Safari (Google/Apple niceties I suppose)
