### ISSUE TITLE
Hyperlink error

### ISSUE THREAD

**Issue by FrancescoVit** [ISA-tools/OntoMaton#15]
Hello,
# ERROR! in the spreadsheet cell is raised when tagging terms with "Place hyperlinked term name in field" option selected.

The formula inserted in the cell contains a comma: 
=HYPERLINK("http://semanticscience.org/resource/SIO_000173","affiliation")

while it should contain a semicolon (manually correcting to semicolon restores the hyperlink): 
=HYPERLINK("http://semanticscience.org/resource/SIO_000173";"affiliation")

Not sure if some sort of bug, or if it depend on local language settings (Italian).

**Comment by eamonnmag** [comment]
Thanks @FrancescoVit! They are known to change their API a bit, so you could be the first one to see their new API. We'll sort this out ASAP.

**Comment by agbeltran** [comment]
Hi @FrancescoVit, this is working in the live version using a comma, and I found this document that confirms that comma is correct https://support.google.com/docs/answer/3093313?hl=en
I'm closing the issue now, but please re-open if you are still facing issues. Many thanks.

**Comment by agbeltran** [comment]
This might have been a change in the API, as @eamonnmag mentioned
