### ISSUE TITLE
'UiApp has been deprecated' Error

### ISSUE THREAD

**Issue by azankl** [ISA-tools/OntoMaton#29]
When I try to go to the 'About' or 'Settings' menu in Ontomaton, I get the following error:

UiApp has been deprecated. Please use HtmlService instead.

Can this be fixed?

**Comment by nandadorea** [comment]
I get the same error, I am not able to move forward with any of the functions, as I just keep getting this same error. Is there some setting I need to tweek on my side? Thanks for all the work in the tool, and thanks in advance for any light into this.

**Comment by nandadorea** [comment]
Also, if I try to search for terms, I get the message "ScriptError: Authorization is required to perform that action."

**Comment by eamonnmag** [comment]
We're working on fixing this now, Google have changed the entire API. Should have updates in a few days!

**Comment by eamonnmag** [comment]
New version is finally available! @azankl @nandadorea 
https://gsuite.google.com/marketplace/app/ontomaton_ontology_search_tagging/846614051855
