### ISSUE TITLE
Still working 

### ISSUE THREAD

**Issue by ypriverol** [ISA-tools/OntoMaton#30]
Is this tool still working. We want to use it in one of our projects

**Comment by eamonnmag** [comment]
Google changed the entire API so we're migrating everything now to get it working. Updates to follow shortly!

**Comment by cbeaulieumd** [comment]
Similarly would love to try OntoMaton when it is back up.  Nothing comes up in search on Google Sheets/Add In...

Chris

**Comment by JCGiron** [comment]
@eamonnmag any progress? I just searched the add-in... no results :(

**Comment by proccaserra** [comment]
Hi @JCGiron, the code has been fixed but we've been delayed by the Google approval process, which is a bit convoluted. We'll see to solve this when we have time. Cheers

**Comment by eamonnmag** [comment]
@JCGiron @ypriverol @cbeaulieumd 
App is now back.
https://gsuite.google.com/marketplace/app/ontomaton_ontology_search_tagging/846614051855
