### ISSUE TITLE
How do I get OntoMaton to show up in Add-ons in a Googlesheet?

### ISSUE THREAD

**Issue by cebriggs7135** [ISA-tools/OntoMaton#31]
How do I get OntoMaton to show up when I search for OntoMaton from Add-ons in a Googlesheet?
I downloaded and opened the tar file but then what?

**Comment by eamonnmag** [comment]
The new version is back now! Google Apps changed the API so the old version was deprecated.

https://gsuite.google.com/marketplace/app/ontomaton_ontology_search_tagging/846614051855
