### ISSUE TITLE
ScriptError: You do not have the necessary permission to access the requested document.

### ISSUE THREAD

**Issue by CavalcanteM** [ISA-tools/OntoMaton#32]
Hi,
Now, i am started to use OntoMaton, but everytime I search a term this error appers:
ScriptError: Non disponi dell'autorizzazione necessaria per accedere al documento richiesto.
Translation:
ScriptError: You do not have the necessary permission to access the requested document.

How can i fix this?

**Comment by eamonnmag** [comment]
I would suggest starting a new project. @proccaserra is the current example sheet not working correctly?

**Comment by proccaserra** [comment]
@eamonnmag @CavalcanteM , well interested one. I can not reproduce. It works for me nicely if using my personal google account.
I then tried with a project specific google account  (the project has 150 members) and creating a new gspreadsheets makes it available to all. 
In this private google drive, members can add add-ons to the spreadsheet. I could install Ontomaton but then ran into the error message reported by @CavalcanteM .

@CavalcanteM are you using a personal google account or is the account part of a private gdrive? 

Ontomaton is vetted for 0-50 users and was wondering if that could be the reason for the error message
