### ISSUE TITLE
the Biological Collections Ontology in BioPortal seems not included in search results

### ISSUE THREAD

**Issue by wouteraddink** [ISA-tools/OntoMaton#33]

**Comment by proccaserra** [comment]
@wouteraddink, thanks for checking in. I was unable to reproduce the issue. See the screen captures below.
the first one is from the `settings` panel
the second one if when running the NCBO Annotator function from a gsheet running Ontomaton add-on
(irrespective of the browser)

Please let us know if you can fetch BCO, (it could have a been a glitch).

<img width="371" alt="image" src="https://user-images.githubusercontent.com/517736/107854287-dcee3f00-6e12-11eb-93a1-17598748e39d.png">

and 

<img width="546" alt="image" src="https://user-images.githubusercontent.com/517736/107854303-f2636900-6e12-11eb-9833-c75a3bc4fea9.png">

**Comment by wouteraddink** [comment]
It is working now, must have been a glitch
